dist: trusty
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - "jruby"
  #  - rbx
  #  - "1.8.7"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
